name: test-pgv15b
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:15beta4
        env:
          POSTGRES_DB: pgeltestdb
          POSTGRES_USER: pgeltestuser
          POSTGRES_PASSWORD: pgeltest
        command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Install Emacs
        run: |
          sudo apt-get update
          sudo apt-get install emacs nettle-bin

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run connection tests
        run: make -C test test test-ssl
