name: Test communication with PostgreSQL server, version 15 beta
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest

    steps:
      - name: Install Emacs
        run: |
          sudo apt-get update
          sudo apt-get install emacs

      - name: Set up PostgreSQL user and database
        uses: Daniel-Marynicz/postgresql-action@master
        with:
           postgres_image_tag: 15beta4
           # We use the superuser for tests, instead of the unprivileged app user,
           # because our tests include creating a database
           postgres_user: pgeltestuser
           postgres_password: pgeltest
           postgres_db: pgeltestdb

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run connection tests
        run: make -C test
