name: test-pgv12
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        # Docker Hub image
        image: postgres:12-alpine
        env:
          POSTGRES_DB: pgeltestdb
          POSTGRES_USER: pgeltestuser
          POSTGRES_PASSWORD: pgeltest
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        volumes:
          - /var/run/postgresql:/var/run/postgresql

    steps:
      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
           version: 29.1

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run connection tests over TCP
        run: make -C test

      - name: Run connection tests over local Unix socket
        run: make -C test test-local
