name: test-macos
on: push

jobs:
  runner-job:
    # using the PostgreSQL version pre-installed on GitHub's MacOS virtual images
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - name: Set up pre-installed PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: pgeltestuser
          password: pgeltest
          database: pgeltestdb
        id: postgres

      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
           version: 29.1

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run connection tests over network
        run: make -C test test
